GET http://localhost:8080/members
Content-Type: application/json

###

GET http://localhost:8080/members/G0001
Content-Type: application/json



###
GET http://localhost:8080/members
Content-Type: application/json